/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Automation": "自动化",
    "Click this box to continue": "单击此框以继续",
    "Grimoire": "魔典",
    "Let's get started!": "让我们开始吧！",
    "Options": "选项",
    "The number shown on them is their Power - you need to have a higher Power than the enemy.": "它们上面显示的数字是他们的力量 —— 你需要拥有比敌人更高的力量。",
    "Towers of Googology": "大数塔",
    "Welcome to Towers of Googology!": "欢迎来到大数塔！",
    "Upgrades": "升级",
    "Your Goal: Defeat All the Reds": "你的目标：击败所有的红方",
    "For touchscreen users: Swiping the screen should also works": "对于触摸屏用户：滑动屏幕也应该有效",
    "Use WASD or arrow keys to move.": "使用 WASD 或箭头键移动。",
    "You are Blue": "你是蓝方",
    "Accumulate 1,500 Fame to unlock something": "累积 1,500 点声望解锁一些东西",
    "Defeat all remaining reds to continue. You can only go to the next tower when your current tower is cleared.": "击败所有剩余的红色以继续。 只有当您当前的塔被清除时，您才能前往下一个塔。",
    "Level Completed!": "关卡完成！",
    "Each level you beaten will award you with Fame. The more Power you have at the end, the more Fame you'll get.": "您击败的每个级别都会授予您声望。 您最终拥有的力量越多，您获得的声望就越多。",
    "You gain all the Power of all defeated enemies.": "你获得所有被击败敌人的所有力量。",
    "You Have Absorb Powers": "你有吸收能力",
    "About": "关于",
    "Back to home page": "返回首页",
    "Bricks": "砖块",
    "Coming soon...": "敬请期待...",
    "Click the \"+\" button to bind a key, click a key to unbind it.": "点击\"+\"按钮绑定一个键，点击一个键解除绑定。",
    "Controls": "控制",
    "created by ducdat0507": "作者为 ducdat0507",
    "Day": "白天",
    "Defeat enemies and grow your towers - incremental style!": "击败敌人并发展你的塔 - 增量风格！",
    "Display": "显示",
    "Down": "下",
    "Elemite": "元素",
    "Export Save": "导出存档",
    "Fame": "声望",
    "Fame Exponent": "声望指数",
    "Fame Multiplier": "声望乘数",
    "Fame Upgrades Unlocked!": "声望升级已解锁！",
    "Flat": "扁平化",
    "General": "常规",
    "Import Save": "导入存档",
    "Karma": "业力",
    "Keybindings": "绑定快捷键",
    "Left": "左",
    "Locked": "未解锁",
    "Loot": "战利品",
    "Make levels slightly bigger and spawn more enemies.": "使等级稍大并产生更多敌人。",
    "Mana": "法力",
    "Manual Save": "手动保存",
    "Night": "夜间",
    "Right": "右",
    "Realm": "领域",
    "Realm Level": "领域等级",
    "RESET GAME": "重置游戏",
    "Save Management": "存档管理",
    "Full Swipe": "全刷",
    "Touch Controls": "触摸控制",
    "Transcendance": "超越",
    "What even is a game without upgrades? Use your Fame to unlock upgrades that, in turn, help you make more Fame!": "没有升级的游戏算什么？ 使用您的声望解锁升级，反过来，帮助您获得更多声望！",
    "World Themes": "世界主题",
    "You can now click this box to dismiss it": "您现在可以单击此框将其关闭",
    "Continuous": "连续",
    "D-Pad": "方向键",
    "Up": "上",
    "Starting Power": "初始力量",
    "Enemy Growth Factor": "敌方成长因子",
    "Fame to Loot": "声望到战利品",
    "Loot Chance": "战利品几率",
    "Abilities": "能力",
    "Loot Multiplier": "战利品乘数",
    "Safepoints": "安全点",
    "You start at the start of the tower instead of the level when died.": "您从塔的起点而不是死亡时的级别开始。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Level ": "等级 ",
    "Scheme: ": "方案：",
    "Unlocks at Realm Level ": "解锁于领域等级 ",
    "Fame Exponent ": "声望指数 ",
    "Increase chances of spawning a Loot by ": "提高产生战利品的几率",
    "Increase Power in Fame gain formula by ": "提高声望增益公式的力量",
    "Make enemies scale faster by ": "使敌人更快地扩大规模 ",
    "Increase amount of Loot that can be spawned by ": "提高可以产生的战利品数量",
    "Loot to Fame": "战利品声望",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Increase your Power at the start of each level by (.+).$/, '在每个级别开始时将你的力量提高 $1。'],
    [/^Increase Fame gain by (.+), before Fame Exponent.$/, '在声望指数之前将声望增益增加 $1。'],
    [/^Increase Loot gain by (.+), additively.$/, '将战利品增益增加 $1，附加。'],
    [/^Increase Fame gain by (.+), additively.$/, '将声望增益增加 $1，附加。'],
    [/^Increase Fame gain by (.+), compounding.$/, '将声望增益增加 $1，复合。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);