/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Automation": "自动化",
    "Click this box to continue": "单击此框以继续",
    "Grimoire": "魔典",
    "Let's get started!": "让我们开始吧！",
    "Options": "选项",
    "The number shown on them is their Power - you need to have a higher Power than the enemy.": "它们上面显示的数字是他们的力量 —— 你需要拥有比敌人更高的力量。",
    "Towers of Googology": "大数塔",
    "Welcome to Towers of Googology!": "欢迎来到大数塔！",
    "Upgrades": "升级",
    "Your Goal: Defeat All the Reds": "你的目标：击败所有的红方",
    "For touchscreen users: Swiping the screen should also works": "对于触摸屏用户：滑动屏幕也应该有效",
    "Use WASD or arrow keys to move.": "使用 WASD 或箭头键移动。",
    "You are Blue": "你是蓝方",
    "Accumulate 1,500 Fame to unlock something": "累积 1,500 点声望解锁一些东西",
    "Defeat all remaining reds to continue. You can only go to the next tower when your current tower is cleared.": "击败所有剩余的红色以继续。 只有当您当前的塔被清除时，您才能前往下一个塔。",
    "Level Completed!": "关卡完成！",
    "Each level you beaten will award you with Fame. The more Power you have at the end, the more Fame you'll get.": "您击败的每个级别都会授予您声望。 您最终拥有的力量越多，您获得的声望就越多。",
    "You gain all the Power of all defeated enemies.": "你获得所有被击败敌人的所有力量。",
    "You Have Absorb Powers": "你有吸收能力",
    "About": "关于",
    "Back to home page": "返回首页",
    "Bricks": "砖块",
    "Coming soon...": "敬请期待...",
    "Click the \"+\" button to bind a key, click a key to unbind it.": "点击\"+\"按钮绑定一个键，点击一个键解除绑定。",
    "Controls": "控制",
    "created by ducdat0507": "作者为 ducdat0507",
    "Day": "白天",
    "Defeat enemies and grow your towers - incremental style!": "击败敌人并发展你的塔 - 增量风格！",
    "Display": "显示",
    "Down": "下",
    "Elemite": "元素",
    "Export Save": "导出存档",
    "Fame": "声望",
    "Fame Exponent": "声望指数",
    "Fame Multiplier": "声望乘数",
    "Fame Upgrades Unlocked!": "声望升级已解锁！",
    "Flat": "扁平化",
    "General": "常规",
    "Import Save": "导入存档",
    "Karma": "业力",
    "Keybindings": "绑定快捷键",
    "Left": "左",
    "Locked": "未解锁",
    "Loot": "战利品",
    "Make levels slightly bigger and spawn more enemies.": "使等级稍大并产生更多敌人。",
    "Mana": "法力",
    "Manual Save": "手动保存",
    "Night": "夜间",
    "Right": "右",
    "Realm": "领域",
    "Realm Level": "领域等级",
    "RESET GAME": "重置游戏",
    "Save Management": "存档管理",
    "Full Swipe": "全刷",
    "Touch Controls": "触摸控制",
    "Transcendance": "超越",
    "What even is a game without upgrades? Use your Fame to unlock upgrades that, in turn, help you make more Fame!": "没有升级的游戏算什么？ 使用您的声望解锁升级，反过来，帮助您获得更多声望！",
    "World Themes": "世界主题",
    "You can now click this box to dismiss it": "您现在可以单击此框将其关闭",
    "Continuous": "连续",
    "D-Pad": "方向键",
    "Up": "上",
    "Starting Power": "初始力量",
    "Enemy Growth Factor": "敌方成长因子",
    "Fame to Loot": "声望到战利品",
    "Loot Chance": "战利品几率",
    "Abilities": "能力",
    "Loot Multiplier": "战利品乘数",
    "Safepoints": "安全点",
    "You start at the start of the tower instead of the level when died.": "您从塔的起点而不是死亡时的级别开始。",
    "Completed!": "已完成!",
    "^x of log(log(Power)) multiplies Brick gain.": "log(log(力量)) 的 ^x 乘以 砖块 增益。",
    "^x of Loot gain multiplies your current Fame.": "^x 的战利品增益乘以您当前的声望。",
    "^x of Realm Level multiplies Brick gain.": "领域级别的 ^x 乘以砖块增益。",
    "Absorb Bonus": "吸收奖励",
    "Base Loot": "基础战利品",
    "Bought": "购买",
    "Bricks to Fame": "砖块到声望",
    "Bricks to Loot": "砖块到战利品",
    "Bulldozer": "推土机",
    "Enemy Absorb Factor": "敌方吸收因子",
    "Fame Duplicator": "声望复制者",
    "Fame Exp. II to Loot": "声望指数II 到战利品",
    "Fame Exp. to Loot": "声望指数 到战利品",
    "Fame Upgrades are no longer priced.": "声望升级不再定价。",
    "Free Fame Upgrades": "免费声望升级",
    "Gain an extra ^x of enemies' Power when killed.": "被杀死时获得额外 ^x 的敌人力量。",
    "II multiplies Loot gain.": "II 乘以战利品增益。",
    "Maxed out": "超出最大",
    "multiplies Loot gain.": "乘以战利品增益。",
    "Random Loot": "随机战利品",
    "Unlock Bricks. You gain Bricks per tower cell when you complete a level.": "解锁砖块。 当您完成一个级别时，您将获得每个塔单元的砖块。",
    "x% of Absorb Bonus affect Enemy Growth Factor.": "x% 的吸收加成影响敌人成长因子。",
    "Absorb Operator Up": "吸收操作符",
    "Absorb the absorb powers of the Earth, making your": "吸收大地的吸收力，使你的",
    "Absorbing multiplies your Fame instead of added.": "吸收会使您的声望成倍增加而不是增加。",
    "Active": "主动",
    "Anti-Active Realm Level": "反主动领域级别",
    "Apply Karma boost upgrades to enemy growth.": "对敌人的成长应用业力提升升级。",
    "Auto Brick Upgrades": "自动砖块升级",
    "Auto Fame Upgrades": "自动声望升级",
    "Auto Karma Pack": "自动业力包",
    "Auto Karma Upgrades": "自动业力升级",
    "Auto Loot Upgrades": "自动战利品升级",
    "Auto Mana Pack": "自动法力包",
    "Auto Mana Upgrades": "自动法力升级",
    "Automatically buy Brick upgrades when you gain Bri": "当您获得 砖块 时自动购买 砖块 升级",
    "Automatically buy Fame upgrades when you gain Fame": "获得 声望 时自动购买 声望 升级",
    "Automatically buy Karma Upgrades when you gain Kar": "获得 业力 时自动购买 业力 升级",
    "Automatically buy Loot upgrades when you gain Loot": "获得 战利品 时自动购买 战利品 升级",
    "Automatically buy Mana Upgrades when you gain Mana": "获得 法力 时自动购买 法力 升级",
    "Automation Control": "自动化控制",
    "Base Loot to Brick": "从基础战利品到砖块",
    "Boosts": "提升",
    "Brick Upgrades": "砖升级",
    "Brick Upgrades are no longer priced.": "砖块升级不再定价。",
    "Charge the rift by casting spells. The more expens": "通过施法为裂隙充能。费用越多",
    "Cooldown: 1 levels": "冷却时间：1级",
    "Decrease cooldown by -1, but also increase cost by": "冷却时间减少 -1，但成本增加",
    "Decrease interval by 2%, but also increase cost by": "间隔减少 2%，但成本增加",
    "Decreases the maximum Active Realm Level by 15%.": "降低最大活跃领域等级 15%。",
    "Easy Bricks": "简单砖块",
    "Easy Fame": "简单声望",
    "Element Improvements": "元素改进",
    "Elemental": "元素",
    "Elemental Spells": "元素法术",
    "Elemite Multiplier": "元素乘数",
    "Elemite Ritual": "元素仪式",
    "Elemite Ritual Exp.": "元素仪式指数",
    "Elemite Ritual Mul.": "元素仪式乘数",
    "Elemite to Karma": "元素到业力",
    "Elemite to Mana": "元素到法力",
    "Embrace the rage of Fire, making the \"Karma to Po": "拥抱火之怒火，使“因果报”",
    "Enter the rift": "进入裂缝",
    "Fame gained from completing levels are multiplied ": "完成关卡获得的声望成倍增加",
    "Fame Operator Up": "名气运营商",
    "Fame to Brick": "成名砖",
    "Fame Upgrades": "声望升级",
    "Free Brick Upgrades": "免费砖升级",
    "Free Fame Upgrades II": "免费声望升级 II",
    "Free Karma Upgrades": "免费 业力 升级",
    "Free Loot Upgrades": "免费战利品升级",
    "Free Loot Upgrades II": "免费战利品升级 II",
    "Free Mana Upgrades": "免费法力升级",
    "Freeze all enemies with Ice, making them unable to": "用冰冻结所有敌人，使他们无法",
    "Gain 1% of Mana gain on Mana Ritual each time you ": "每次你在法力仪式上获得 1% 的法力增益",
    "Gain an extra ↑↑x of Power when you kill an enemy.": "杀死敌人时获得额外的 ↑↑x 点能量。",
    "Gain Bricks when complete a tower instead of a lev": "完成塔而不是 lev 时获得砖块",
    "Gain Fame when complete a tower instead of a level": "完成一座塔而不是一个关卡时获得声望",
    "Gain x Karma on player move.": "玩家移动时获得 x 业力。",
    "Gain x×cbrt(Realm Level) Karma on tower complete.": "在塔完成时获得 x×cbrt(领域等级) 业力。",
    "Gain x×sqrt(Realm Level) Karma on level complete.": "在关卡完成时获得 x×sqrt(领域等级) 业力。",
    "Increase duration by +1, but also increase cost by": "持续时间增加+1，但成本增加",
    "Increase effect by ×+0.1, but also increase cost b": "增加效果×+0.1，但也增加成本b",
    "Increase Elemite gain by ×+0.2, additively.": "将 元素 增益增加 ×+0.2，相加。",
    "Increase Elemite to Mana and Karma gain per upgrad": "每次升级增加 元素 到 法力 和 业力 增益",
    "Increase Karma gain by ×1.05, compounding.": "将业力增益增加 ×1.05，复合。",
    "Increase M.M.K.K.M.K.K. gain per upgrade.": "增加 M.M.K.K.M.K.K.每次升级获得。",
    "Increase Mana gain by ×1.05, compounding.": "法力增益增加 ×1.05，复合。",
    "Increases Elemite gain by ×+0.2, additively.": "额外增加元素增益×+0.2。",
    "Karma to Brick": "业力到砖块",
    "Karma to Elemite": "业力到元素",
    "Karma to Fame": "声望的业力",
    "Karma to Loot": "业力到战利品",
    "Karma to Loot to Bricks": "业力到战利品到砖块",
    "Karma to Loot to Bricks also affect enemy growth.": "业力到战利品到砖块 也会影响敌人的成长。",
    "Karma to Loot to E.G.F.": "业力到战利品到E.G.F.",
    "Karma to Loot to Fame": "业力到战利品到声望",
    "Karma to Loot to Power": "业力到战利品到力量",
    "Karma to Loot to Power also affect Bricks.": "业力到战利品到力量 也会影响砖块。",
    "Karma to Loot to Power also affect Power and enemy": "业力到战利品到力量 也会影响力量和敌人",
    "Karma to Mana": "业力到法力",
    "Karma Upgrades": "业力升级",
    "Karma Upgrades are no longer priced.": "Karma 升级不再定价。",
    "Keep \"Free Fame Upgrades\" on Mana Rituals.": "在法力仪式上保留“免费声望升级”。",
    "Keep \"Free Loot Upgrades\" on Mana Rituals.": "在法力仪式上保持“免费战利品升级”。",
    "Lean yourself to the Wind, and let the game play i": "靠在风中，让游戏玩我",
    "Loot gained from tiles are multiplied instead of a": "从瓷砖获得的战利品成倍增加而不是",
    "Loot Operator Up": "掠夺操作员",
    "Loot to Brick": "抢到砖头",
    "Loot Upgrades": "战利品升级",
    "Loot Upgrades are no longer priced.": "战利品升级不再定价。",
    "M.M.K.K.M.K.K.": "M.M.K.K.M.K.K.",
    "M.M.K.K.M.K.K. DX": "M.M.K.K.M.K.K. DX",
    "M.M.K.K.M.K.K. II": "M.M.K.K.M.K.K.二",
    "Mana Fountain": "法力喷泉",
    "Mana Ritual": "法力仪式",
    "Mana to Karma": "法力到业力",
    "Mana Upgrades": "法力升级",
    "Mana Upgrades are no longer priced.": "法力升级不再定价。",
    "Multiplies Absorb Bonus III gain per upgrade by +1": "将每次升级的吸收奖励 III 增益乘以 +1",
    "Multiplies Karma gain by ×+0.5, additively.": "将 业力 增益乘以 ×+0.5，相加。",
    "Multiplies Mana gain by ×+0.25, additively.": "将法力增益乘以 ×+0.25，相加。",
    "Multiplies Player Karma gain by x% of sqrt(Level K": "将玩家业力增益乘以 sqrt(等级 业力",
    "Multiplies Player Karma gain per upgrade by +0.05.": "每次升级将玩家业力增益乘以 +0.05。",
    "Multiplies Tower Karma gain by x% of sqrt(Level Ka": "将 塔业力 增益乘以 sqrt(等级 业力) 的 x%",
    "Multiply Elemite Ritual gain by ×1.25, additively.": "将 元素 仪式增益乘以 ×1.25，相加。",
    "Raise Elemite Ritual gain by ^+0.05, additively.": "将 元素 仪式增益提高 ^+0.05，相加。",
    "Random Loot to Brick": "随机战利品到砖",
    "Retain Free Karma Upgrades and Auto Karma Upgrades": "保留免费 业力 升级和自动 业力 升级",
    "Retain Free Mana Upgrades and Auto Mana Upgrades o": "保留免费法力升级和自动法力升级 o",
    "Select a Ritual": "选择仪式",
    "Spell of Earth": "地之法术",
    "Spell of Earth S": "地之法术 S",
    "Spell of Earth+": "之法术+",
    "Spell of Fire": "火之法术",
    "Spell of Fire S": "火之法术 S",
    "Spell of Fire+": "火之法术+",
    "Spell of Ice": "冰之法术",
    "Spell of Ice S": "冰之法术 S",
    "Spell of Ice+": "冰之法术+",
    "Spell of Wind": "风之法术",
    "Spell of Wind S": "风之法术",
    "Spell of Wind+": "风之法术+",
    "Spell of Wind++": "风之法术++",
    "Tetrates Brick gain by ↑↑+0.01, additively.": "四次方 砖块 增益 ↑↑+0.01，附加。",
    "Tetrates Fame gain by ↑↑+0.01, additively.": "四次方 声望增加 ↑↑+0.01，附加。",
    "Tetrates Loot gain by ↑↑+0.01, additively.": "四次方 战利品增益 ↑↑+0.01，附加。",
    "The Arts of Elements": "元素艺术",
    "The Elemental": "元素",
    "The Rift": "裂隙",
    "The rift is silent.": "裂隙沉默了。",
    "The Ritual": "仪式",
    "to Player": "到玩家",
    "to Tower": "到塔",
    "Tower Karma": "塔业",
    "Unlocks Elemite upgrades.": "解锁 元素 升级。",
    "Unlocks the Elemental system, which allows you to ": "解锁元素系统，让您能够",
    "Unlocks The Grimoire and The Ritual, which allows ": "解锁魔典和仪式，这允许",
    "Unlocks the Rift.": "解锁裂隙。",
    "WARNING: The Ritual": "警告：仪式",
    "x% of Absorb Bonus III (min. ↑↑2) affects enemy gr": "吸收奖励 III (min. ↑↑2)的 x% 影响敌人成长",
    "Your Fame is tetrated by Karma to Loot and Base Lo": "你的声望被 业力 提升到 战利品 和 基础战利品",
    "Your progress in The Rift increases M.M.K.K.M.K.K.": "你在裂隙的进度会增加 M.M.K.K.M.K.K.",
    "^x of Base Loot multiplies Brick gain.": "基础战利品的 ^x 乘以砖块增益。",
    "^x of Fame Exponent II multiplies Brick gain.": "声望指数 II 的 ^x 乘以砖块增益。",
    "^x of Fame Exponent multiplies Brick gain.": "名望指数的 ^x 乘以砖块增益。",
    "^x of log(Karma) multiplies Elemite gain.": "log(业力) 的 ^x 乘以 元素 增益。",
    "^x of log(log(log(Fame))) multiplies Brick gain.": "log(log(log(声望))) 的^x 乘以砖块增益。",
    "^x of log(log(Loot)) multiplies Brick gain.": "^x of log(log(战利品)) 乘以砖块增益。",
    "^x of log(Mana) multiplies Elemite gain.": "log(法力) 的 ^x 乘以 元素 增益。",
    "^x of Random Loot multiplies Brick gain.": "^x 的随机战利品乘以砖块增益。",
    "Absorb the absorb powers of the Earth, making your Karma gain 2× better for the next 10 levels.": "吸收大地的吸收力，使您的业力在接下来的 10 个级别中获得 2 倍的提升。",
    "Automatically buy Brick upgrades when you gain Bricks.": "当您获得积木时自动购买积木升级。",
    "Automatically buy Fame upgrades when you gain Fame.": "获得声望时自动购买声望升级。",
    "Automatically buy Karma Upgrades when you gain Karma.": "当您获得 业力 时自动购买 业力 升级。",
    "Automatically buy Loot upgrades when you gain Loot.": "获得战利品时自动购买战利品升级。",
    "Automatically buy Mana Upgrades when you gain Mana.": "获得法力时自动购买法力升级。",
    "Charge the rift by casting spells. The more expensive the spell, the more charge it gives.": "通过施法为裂隙充能。法术越昂贵，它提供的能量就越多。",
    "Decrease cooldown by -1, but also increase cost by ×1.2.": "冷却时间减少-1，但成本增加×1.2。",
    "Decrease interval by 2%, but also increase cost by ×1.1.": "间隔减少2%，成本增加×1.1。",
    "Embrace the rage of Fire, making the \"Karma to Power\" and \"Karma to Loot to Fame\" effect to Fame 2× better for the next 10 levels.": "拥抱火焰之怒，使“业力到力量”和“业力到战利品到声望”效果在接下来的 10 个级别中提高 2 倍。",
    "Fame gained from completing levels are multiplied instead of added.": "完成关卡获得的声望是成倍增加而不是增加。",
    "Freeze all enemies with Ice, making them unable to attack and can be absorbed regardless of their Power for the next 47 levels.": "用冰冻结所有敌人，使其在接下来的 47 个等级内无法攻击并且可以被吸收，无论他们的力量如何。",
    "Gain 1% of Mana gain on Mana Ritual each time you clear a tower.": "每次清除一座塔时，在法力仪式上获得 1% 的法力增益。",
    "Gain Bricks when complete a tower instead of a level.": "完成塔而不是关卡时获得砖块。",
    "Gain Fame when complete a tower instead of a level.": "完成一座塔而不是一个关卡时获得声望。",
    "Increase duration by +1, but also increase cost by ×1.1.": "持续时间增加+1，但成本增加×1.1。",
    "Increase effect by ×+0.1, but also increase cost by ×1.1.": "增加效果×+0.1，同时增加×1.1的费用。",
    "Increase Elemite to Mana and Karma gain per upgrade.": "每次升级将 元素 增加到 法力 和 业力 增益。",
    "IV": "四",
    "Karma to Loot to Power also affect Power and enemy growth.": "业力到战利品到力量 也会影响力量和敌人的成长。",
    "Lean yourself to the Wind, and let the game play itself (badly) for the next 30 levels. Can be toggled in the Automation tab, but it'll still be counted when off.": "让自己顺风顺水，让游戏在接下来的 30 个关卡中（糟糕地）发挥作用。可以在“自动化”选项卡中切换，但关闭时仍会被计算在内。",
    "Loot gained from tiles are multiplied instead of added.": "从瓷砖获得的战利品会成倍增加而不是增加。",
    "Multiplies Absorb Bonus III gain per upgrade by +1.": "将每次升级的吸收奖励 III 增益乘以 +1。",
    "Multiplies Player Karma gain by x% of sqrt(Level Karma).": "将玩家业力增益乘以 sqrt（等级业力）的 x%。",
    "Multiplies Tower Karma gain by x% of sqrt(Level Karma).": "将 塔业力 增益乘以 sqrt(等级业力) 的 x%。",
    "Retain Free Karma Upgrades and Auto Karma Upgrades on Elemite Rituals.": "保留 元素 仪式的免费 业力 升级和自动 业力 升级。",
    "Retain Free Mana Upgrades and Auto Mana Upgrades on Elemite Rituals.": "保留 元素 仪式的免费法力升级和自动法力升级。",
    "Unlocks the Elemental system, which allows you to cast temporary spells.": "解锁元素系统，让您可以施展临时法术。",
    "Unlocks The Grimoire and The Ritual, which allows you to \"reborn\".": "解锁魔法书和仪式，让你“重生”。",
    "x% of Absorb Bonus III (min. ↑↑2) affects enemy growth.": "x% 的吸收奖励 III（最小 ↑↑2）影响敌人的成长。",
    "Your Fame is tetrated by Karma to Loot and Base Loot amount when you gain Loot.": "当你获得战利品时，你的声望会被业力四分到战利品和基础战利品数量。",
    "Your progress in The Rift increases M.M.K.K.M.K.K. II.": "你在 裂隙 的进度会增加 M.M.K.K.M.K.K. II。",
    "Click this box to dismiss": "单击此框以关闭",
    "Hold an upgrade to buy the most that you can buy at once - plus, only the last one is actually priced!": "举行一次升级以购买您一次可以购买的最多 - 而且，只有最后一个才是真正的定价！",
    "Buy Max Unlocked!": "购买最大已解锁！",
    "Loot Unlocked!": "战利品已解锁！",
    "Loot are spawned on the playfield as yellow and gives their own currency when taken. They also do not require having a higher Power, nor increase yours.": "战利品在操场上产生为黄色，并在被拿走时提供自己的货币。 他们也不需要拥有更高的力量，也不需要增加你的力量。",
    "Bricks Unlocked!": "砖块已解锁！",
    "You'll now bulldoze towers when you complete a level, which will give you Bricks based on how large the level is. Brick Upgrades' buy max don't work like other upgrades - all upgrades will be priced!": "现在，当您完成一个关卡时，您将推平塔楼，这将根据关卡的大小为您提供砖块。 砖块升级 的购买上限与其他升级不同 - 所有升级都将定价！",
    "Grimoire Unlocked!": "魔典解锁！",
    "You are now capable of casting dark magic! The first available spell is \"The Ritual\", which allows you to \"reborn\" - reset everything to get a new currency called \"Mana\". Everything will grow very fast from now on, so you'll reach the point before reset in no time.": "你现在可以施展黑暗魔法了！ 第一个可用的咒语是“仪式”，它允许您“重生”——重置一切以获得一种名为“法力”的新货币。 从现在开始，一切都会变得非常快，所以你很快就会到达重置前的地步。",
    "F Notation?": "F 符号？",
    "You Fame has gone so big it needs to be expresed into a different notation!\n1Fx means 1ee...ee1 with x e's.": "你的声望 变得如此之大，需要用不同的符号来表达！\n1Fx 表示 1ee...ee1 和 x e。",
    "Max Active Realm Level Reached!": "达到最大主动领域级别！",
    "The generated levels won't become anymore difficult after Realm Level 1,000, but you can still upgrade it to increase your Karma gain!": "境界1000后生成的关卡不会再难了，但你还是可以升级它来增加你的业力增益！",
    "Elemental System Unlocked!": "元素系统解锁！",
    "The Elemental system allows you to cast powerful temporary spells with a cost of Elemite, which can be found by getting Loot. These spells can be accessed in the Grimoire tab.": "元素系统允许你以 元素 为代价施展强大的临时法术，这可以通过获得 战利品 来找到。 这些法术可以在魔法书标签中访问。",
    "The Rift Unlocked!": "裂隙解锁！",
    "Click this box to dismiss...?": "单击此框以关闭...？",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Level ": "等级 ",
    "Scheme: ": "方案：",
    "Unlocks at Realm Level ": "解锁于领域等级 ",
    "Fame Exponent ": "声望指数 ",
    "Increase chances of spawning a Loot by ": "提高产生战利品的几率",
    "Increase Power in Fame gain formula by ": "提高声望增益公式的力量",
    "Make enemies scale faster by ": "使敌人更快地扩大规模 ",
    "Increase amount of Loot that can be spawned by ": "提高可以产生的战利品数量",
    "Loot to Fame": "战利品声望",
    "Brick Power": "砖块力量",
    "Increase the base Loot modifier by ": "增加基础战利品修饰",
    "Increase the random Loot modifier by ": "增加随机战利品修饰",
    "Absorb Bonus ": "吸收奖励 ",
    "Player Karma": "玩家业力",
    "Mana to Elemite": "法力到元素",
    "Enemy Absorb Bonus": "敌人吸收奖励",
    "Enemy Absorb Factor": "敌人吸收因子",
    "Fame Exp. to Brick": "声望指数到砖块",
    "Next at ": "下一个在",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^⣿⠅⠄(.+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Increase your Power at the start of each level by (.+).$/, '在每个级别开始时将你的力量提高 $1。'],
    [/^Raises Fame gain by (.+), compounding.$/, '将声望增益提高 $1，复合。'],
    [/^Increase Loot gain by (.+), compounding.$/, '增加战利品增益 $1，复合。'],
    [/^Increase Fame gain by (.+), before Fame Exponent.$/, '在声望指数之前将声望增益增加 $1。'],
    [/^Increase Loot gain by (.+), additively.$/, '将战利品增益增加 $1，附加。'],
    [/^Increase Fame gain by (.+), additively.$/, '将声望增益增加 $1，附加。'],
    [/^Increase Fame gain by (.+), compounding.$/, '将声望增益增加 $1，复合。'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) turns$/, '$1 回合'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) \/ (.+) elves$/, '成本：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);